ALTER TABLE brands ADD COLUMN address VARCHAR(500);
ALTER TABLE brands ADD COLUMN city VARCHAR(100);
ALTER TABLE brands ADD COLUMN state VARCHAR(100);
ALTER TABLE brands ADD COLUMN pincode VARCHAR(10);
ALTER TABLE brands ADD COLUMN phone VARCHAR(15);